package ch.supsi.webapp.web.service;

import ch.supsi.webapp.web.model.entity.*;
import ch.supsi.webapp.web.repository.*;
import ch.supsi.webapp.web.model.RequestStatus;
import com.google.common.collect.Lists;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import javax.annotation.PostConstruct;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


// Logica applicativa lato server
// create database bottani CHARACTER SET=latin1
@Service
public class BlogPostService {

    @Autowired
    BlogPostRepository blogPostRepository;

    @Autowired
    UserRepository userRepository;

    @Autowired
    private RoleRepository roleRepository;

    @Autowired
    private CategoryRepository categoryRepository;

    @Autowired
    private CommentRepository commentRepository;

    @PostConstruct
    public void init() {
        if (userRepository.findAll().size() == 0) {
            roleRepository.save(new Role("ROLE_USER"));
            roleRepository.save(new Role("ROLE_ADMIN"));
            User admin = new User(
                    "admin",
                    new Role("ROLE_ADMIN"),
                    new BCryptPasswordEncoder().encode("admin"));
            userRepository.save(admin);

        }

        if (categoryRepository.findAll().size() == 0) {
            categoryRepository.save(new Category("Cultura"));
            categoryRepository.save(new Category("Scienza"));
            categoryRepository.save(new Category("Sport"));
        }
        User admin = new User(
                "admin",
                new Role("ROLE_ADMIN"),
                new BCryptPasswordEncoder().encode("admin"));

        BlogPost b = new BlogPost();
        b.setUser(admin);
        b.setText("Hello");
        b.setTitle("Autogenerated");
        b.setCategory(new Category("Cultura"));

        Comment c = new Comment();
        c.setText("This is interesting");
        c.setUser(admin);

        commentRepository.save(c);

        b.getComment().add(c);

        Comment c1 = new Comment();
        c1.setText("Wow great!");
        c1.setUser(admin);

        Comment c3 = new Comment();
        c3.setText("Indeed");
        c3.setUser(admin);
        c1.getSubc().add(c3);
        commentRepository.save(c3);
        commentRepository.save(c1);
        b.getComment().add(c1);
        blogPostRepository.save(b);
    }


    public BlogPost get(long id) {
        return blogPostRepository.findById(id).get();
    }

    List<BlogPost> filterDeletedBlogPost(List<BlogPost> blogPosts) {
        List<BlogPost> filtered = new ArrayList<BlogPost>();
        if (blogPosts != null) {
            for (BlogPost blog : blogPosts) {
                if (!blog.isDeleted()) filtered.add(blog);
            }
            return filtered;
        } else return new ArrayList<>();
    }
    List<BlogPost> filterNonDeletedBlogPost(List<BlogPost> blogPosts) {
        List<BlogPost> filtered = new ArrayList<BlogPost>();
        if (blogPosts != null) {
            for (BlogPost blog : blogPosts) {
                if (blog.isDeleted()) filtered.add(blog);
            }
            return filtered;
        } else return new ArrayList<>();
    }

    public List<BlogPost> getAll(int size) {
        User a = new User(
                "admin",
                new Role("ROLE_ADMIN"),
                new BCryptPasswordEncoder().encode("admin"));
        //      blogPostRepository.findAllByUserAndTitleContainingOrderByTitle(a, "Ciao").forEach(e -> System.out.println(e.getTitle()));
        //      System.out.println("%%%%");
        //      blogPostRepository.findAllContainingTitle("Ciao").forEach(e -> System.out.println(e.getTitle()));

        List<BlogPost> blogPosts = blogPostRepository.findAll(PageRequest.of(0, size, Sort.Direction.DESC, "date")).getContent();
        return filterDeletedBlogPost(blogPosts);
    }

    public List<BlogPost> searchAll(Category category) {

        return filterDeletedBlogPost(blogPostRepository.findByCategory(category));
    }

    public ResponseEntity<BlogPost> add(BlogPost blogPost) {
        blogPostRepository.save(blogPost);
        return new ResponseEntity<>(blogPost, HttpStatus.OK);
    }

    public ResponseEntity<RequestStatus> delete(long id) {
        BlogPost blogPost = blogPostRepository.findTop1ById(id);
        if (blogPost != null) {
            blogPost.setDeleted(true);
            blogPostRepository.save(blogPost);
            //blogPostRepository.delete(blogPost);
            return new ResponseEntity<>(new RequestStatus(true), HttpStatus.NO_CONTENT);
        }
        return new ResponseEntity<>(new RequestStatus(false), HttpStatus.NOT_FOUND);
    }

    public ResponseEntity<RequestStatus> update(long id, BlogPost blogPost) {
        BlogPost oldBlogPost = blogPostRepository.findTop1ById(id);
        if (oldBlogPost != null) {
            if (blogPost.getUser() != null) {
                oldBlogPost.setUser(blogPost.getUser());
            }
            if (blogPost.getTitle() != null) {
                oldBlogPost.setTitle(blogPost.getTitle());
            }
            if (blogPost.getText() != null) {
                oldBlogPost.setText(blogPost.getText());
            }
            if (blogPost.getCategory() != null) {
                oldBlogPost.setCategory(blogPost.getCategory());
            }
            blogPostRepository.save(oldBlogPost);
            return new ResponseEntity<>(new RequestStatus(true), HttpStatus.NO_CONTENT);
        }

        return new ResponseEntity<>(new RequestStatus(false), HttpStatus.NOT_FOUND);
    }

    public List<BlogPost> getAllBlogPosts() {
        return Lists.newArrayList(blogPostRepository.findAll());
    }

    public long numOfPosts() {
        return blogPostRepository.count();
    }

    public List<User> getAllUsers() {
        return Lists.newArrayList(userRepository.findAll());
    }

    public List<Role> getAllRoles() {
        return Lists.newArrayList(roleRepository.findAll());
    }

    public List<Category> getAllCategories() {
        return Lists.newArrayList(categoryRepository.findAll());
    }

    public User findUserByUsername(String username) {
        return userRepository.findById(username).get();
    }

    public void addUser(User newUser) {
        User admin = new User(
                newUser.getUserName(),
                new Role("ROLE_USER"),
                new BCryptPasswordEncoder().encode(newUser.getPassword()));
        userRepository.save(admin);
    }

    public List<BlogPost> getCancellati(int numOfPosts) {
        List<BlogPost> blogPosts = blogPostRepository.findAll(PageRequest.of(0, numOfPosts, Sort.Direction.DESC, "date")).getContent();
        return filterNonDeletedBlogPost(blogPosts);
    }
}
